/** Declaration file generated by dts-gen */

declare class index {
    constructor(...args: any[]);

    del(...args: any[]): void;

    each(...args: any[]): void;

    get(...args: any[]): void;

    getKey(...args: any[]): void;

    has(...args: any[]): void;

}

